tasks:
  - init: |
      echo 'TODO: install lynx direnv tor'
      sudo apt-get install lynx direnv tor -y
    command: |
      echo 'TODO: start app'
      npm install
      echo 'TODO:Good!!!'

vscode:
  extensions:
    # - ms-python.python
    # - ms-toolsai.jupyter
    # - d-biehl.robotcode
    # - magicstack.magicpython
    - formulahendry.code-runner